[shell]
program = "/bin/zsh"  # Example for Linux/BSD/macOS

[font]
size = 14

[font.normal]
family = "FiraMono Nerd Font"

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"
padding = { x = 15, y = 28 }
